# Generated by Django 6.0.6 on 2026-06-28 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enchere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix_depart', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_actuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_reserve', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='ouverte', max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEnchere.categorie')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encheres', to='accounts.profilutilisateur')),
            ],
        ),
    ]
