# Generated by Django 6.0.6 on 2026-06-28 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='encheres/')),
                ('enchere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='VEnchere.enchere')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('enchere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VEnchere.enchere')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilutilisateur')),
            ],
            options={
                'ordering': ['-montant'],
            },
        ),
    ]
