# Generated by Django 6.0.6 on 2026-06-28 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0002_media_offre'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_externe', models.CharField(blank=True, max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais_plateforme', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('paypal', 'Paypal'), ('stripe', 'Stripe'), ('mobile_money', 'Mobile Money')], max_length=30)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('effectue', 'Effectué'), ('rembourse', 'Remboursé')], default='attente', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('est_livre', models.BooleanField(default=False)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='accounts.profilutilisateur')),
                ('enchere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VEnchere.enchere')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VEnchere.paiement')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='accounts.profilutilisateur')),
            ],
        ),
    ]
