# Generated by Django 6.0.6 on 2026-06-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0003_paiement_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='transaction_externe',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='acheteur',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vendeur',
        ),
    ]
