# Generated by Django 6.0.6 on 2026-06-29 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0004_remove_paiement_transaction_externe_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enchere',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='offre',
            name='enchere',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VEnchere.enchere'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('En enchere', 'En enchère'), ('Vendu', 'Vendu'), ('Retire', 'Retiré')], default='Disponible', max_length=20)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=20)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_creation', models.DateTimeField()),
                ('reference', models.CharField(max_length=50)),
                ('categorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VEnchere.categorie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilutilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='enchere',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VEnchere.produit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
