# Generated by Django 5.2.16 on 2026-08-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0005_remove_enchere_categorie_alter_offre_enchere_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, upload_to='produit/'),
        ),
    ]
