# Generated by Django 5.2.16 on 2026-08-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0006_produit_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='photo',
        ),
        migrations.CreateModel(
            name='produit_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='photoProduits/')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='VEnchere.produit')),
            ],
        ),
    ]
