# Generated by Django 5.2.16 on 2026-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0007_remove_produit_photo_produit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='poids',
            field=models.CharField(max_length=20),
        ),
    ]
