# Generated by Django 5.2.16 on 2026-08-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0008_alter_produit_poids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='couleur',
        ),
    ]
