# Generated by Django 5.2.16 on 2026-08-10 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0009_remove_produit_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
