# Generated by Django 5.2.16 on 2026-08-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0010_alter_produit_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEnchere.categorie'),
        ),
    ]
