# Generated by Django 5.2.16 on 2026-08-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0011_alter_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enchere',
            name='prix_actuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='enchere',
            name='prix_reserve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
