# Generated by Django 5.2.16 on 2026-08-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0012_alter_enchere_prix_actuel_alter_enchere_prix_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enchere',
            name='prix_actuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='enchere',
            name='prix_reserve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
