# Generated by Django 5.2.16 on 2026-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0013_alter_enchere_prix_actuel_alter_enchere_prix_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='statut_validation',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='attente', max_length=20),
        ),
    ]
