# Generated by Django 5.2.16 on 2026-09-09 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEnchere', '0014_produit_statut_validation'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='enchere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VEnchere.enchere'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='accounts.profilutilisateur')),
                ('enchere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='VEnchere.enchere')),
            ],
            options={
                'ordering': ['-date_inscription'],
                'constraints': [models.UniqueConstraint(fields=('acheteur', 'enchere'), name='unique_participation')],
            },
        ),
    ]
